apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

patchesStrategicMerge:
- deployment-patch.yml

images:
- name: faceit-api
  newTag: v0.4.1
- name: faceit-web
  newTag: v0.4.1

configMapGenerator:
- name: faceit-config
  behavior: merge
  literals:
  - ENVIRONMENT=production
  - DOMAIN=pattmsc.online
