apiVersion: apps/v1
kind: Deployment
metadata:
  name: faceit-api
  namespace: faceit-prod
spec:
  replicas: 1

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: faceit-web
  namespace: faceit-prod
spec:
  replicas: 1

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: faceit-celery-worker
  namespace: faceit-prod
spec:
  replicas: 1

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: faceit-postgres
  namespace: faceit-prod
spec:
  replicas: 1

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: faceit-redis
  namespace: faceit-prod
spec:
  replicas: 1
