apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yml
- configmap.yml
- secret.yml
- statefulset-postgres.yml
- deployment-redis.yml
- deployment-api.yml
- deployment-web.yml
- hpa.yml
- ingress.yml

commonLabels:
  environment: production

images:
- name: faceit-api
  newTag: v0.4.0
- name: faceit-web
  newTag: v0.4.0
