apiVersion: v1
kind: Secret
metadata:
  name: faceit-secrets
type: Opaque
stringData:
  SECRET_KEY: "your-secret-key"
  FACEIT_API_KEY: "your-faceit-api-key"
  FACEIT_CLIENT_ID: "your-faceit-client-id"
  FACEIT_CLIENT_SECRET: "your-faceit-client-secret"
  GROQ_API_KEY: "your-groq-api-key"
  DB_PASSWORD: "your-db-password"
  REDIS_PASSWORD: "your-redis-password"
  GF_PASSWORD: "your-grafana-password"
  YOOKASSA_SHOP_ID: "your-yookassa-shop-id"
  YOOKASSA_SECRET_KEY: "your-yookassa-secret-key"
