apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: faceit-uploads-ingress
  namespace: faceit-prod
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "1g"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - uploads.pattmsc.online
    secretName: faceit-uploads-tls
  rules:
  - host: uploads.pattmsc.online
    http:
      paths:
      - path: /demos/
        pathType: Prefix
        backend:
          service:
            name: faceit-uploads-nginx
            port:
              number: 8080
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: faceit-api
            port:
              number: 8000
